@startuml
start

:建立資料陣列;

repeat :收封包;

if(是開始封包) then(是)
  :清空資料陣列;
else(否)
endif

:資料放入陣列;

repeat while (是結束封包) is (否) not (是)

:讀出陣列內容;

if(是加密資料)then(是)
  :解密;
  ' 加入怎麼解密
else(否)
endif

:根據item code 幹活;

stop
@enduml
