@startuml
|Sesame(APP)|
start 
:按下新增按鈕;
|Sesame(APP)|
:發送{device_name, public_key, secret_key};
|Sesame_Touch|
:發送{接收成功};
:讀出{device_name, public_key, secret_key};
:用device_name搜尋藍牙地址;
:儲存{device_name, public_key, secret_key, 藍牙地址};
stop
@enduml
