@startuml
發送 -> 發送: 收到資料 : A A A A B B B B C C C C
發送 -> 發送: 拆解資料 : A A A A
發送 -> 接收: 加上封包頭 : 1 A A A A
接收 -> 接收: 收到 : 1 A A A A
接收 -> 接收: 判斷資料還沒送完，等下一個封包
發送 -> 發送: 拆解資料 : B B B B
發送 -> 接收: 加上封包頭 : 0 B B B B
接收 -> 接收: 收到 : 0 B B B B
接收 -> 接收: 判斷資料還沒送完，等下一個封包
發送 -> 發送: 拆解資料 : C C C C
發送 -> 接收: 加上封包頭 : 2 C C C C
接收 -> 接收: 收到 : 2 C C C C
接收 -> 接收: 資料接收完成，組合封包
接收 -> 接收: 去除封包頭還原資料 : A A A A B B B B C C C C
@enduml
