@startuml
|Sesame(APP)|
start 
:ccmkey A = AES_CMAC(token, random code);
:發送{登入命令, ccmkey A};
|Sesame5|
:ccmkey S = AES_CMAC(token, random code);

if(ccmkey A == ccmkey S) then (是)
  :取出ssm5 timestamp;
  :回傳{登入成功, ssm5 timestamp};
  :發送{ssm5 機械設定};
  :發送{ssm5 機械狀態};
  :設定連線狀態為Login;  
  stop
else (否)
  :登入失敗
  跟手機斷線;
  stop
endif


|Sesame(APP)|
if(abs(APP timestamp – ssm5 timestamp) >=3); then (否)
  stop
else(是)
  :發送{手機 timestamp};
  |Sesame5|
  :更新 ssm5 timestam;
  stop
endif

@enduml
